# docker-compose.yml
version: '2'

services:
  storage:
    image: poncheska/sa-storage:latest
    ports:
      - "8081:8080"

  getter:
    image: poncheska/sa-data-getter:latest
    ports:
      - "8082:8080"
    links:
      - storage

  collector:
    image: poncheska/sa-data-collector:latest
    ports:
      - "8083:8080"
    links:
      - storage
