# docker-compose.yml
version: '2'

services:
  nats:
    image: nats

  storage:
    image: poncheska/sa-storage-v2:latest
    links:
      - nats

  getter1:
    image: poncheska/sa-data-getter-v2:latest
    links:
      - nats

  getter2:
    image: poncheska/sa-data-getter-v2:latest
    links:
      - nats

  getter3:
    image: poncheska/sa-data-getter-v2:latest
    links:
      - nats

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  collector:
    image: poncheska/sa-data-collector-v2:latest
    links:
      - nats
      - postgres

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    links:
      - getter1
      - getter2
      - getter3
      - collector
