# docker-compose.yml
version: '2'

services:
  storage:
    image: poncheska/sa-storage
    ports:
      - "8081:8080"

  getter:
    image: poncheska/sa-data-getter
    ports:
      - "8082:8080"

  collector:
    image: poncheska/sa-data-collector
    ports:
      - "8083:8080"
