# docker-compose.yml
version: '2'

services:
  nats:
    image: nats
    ports:
      - "4222:4222"

  storage:
    image: poncheska/sa-storage-v2:latest
    ports:
      - "8081:8080"
    links:
      - nats

  getter:
    image: poncheska/sa-data-getter-v2:latest
    ports:
      - "8082:8080"
    links:
      - nats

  collector:
    image: poncheska/sa-data-collector-v2:latest
    ports:
      - "8083:8080"
    links:
      - nats
